
# Set environment variables

- name: Set environment variables
  lineinfile:
    name: /etc/environment
    state: present
    line: 'DEV_MACHINE="true"'        

# Make bin dir

- name: Create ~/bin
  file:
    path: ~/bin
    state: directory
    mode: 0755
  become: true
  become_user: "{{ vm_user }}"

# Install additional PPAs

- name: Install extra apt PPAs
  apt_repository: 
    repo: "{{ item }}"
  with_items: "{{ apt_extra_ppa }}"
  when: apt_extra_ppa | length

# Keep apt packages up to date

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # twenty-four hours

- name: Upgrade apt packages
  apt:
    upgrade: safe

# Install extra packages

- name: Install extra apt packages
  apt: 
    pkg: "{{ apt_extra_packages }}"
  when: apt_extra_packages | length

# Install extra Python packages

- name: Install extra pip packages
  pip:
    name: "{{ pip_extra_packages }}"

# Generate language file

- name: Install locale(s)
  locale_gen:
    name: de_DE.UTF-8
    state: present
