---

#######################################################################################
#                                                                                     #
# Vagrant                                                                             #
#                                                                                     #  
#######################################################################################

vagrant: 
  
  # Folders to sync into guest machine
  
  # sync_folders:
  #   - 
  #     from: ../../src
  #     to: /var/www/my-site
  #     args:
  #       id: src
  #       owner: vagrant
  #       group: www-data
  #       mount_options: ["dmode=775,fmode=664"]

# The hostname of the VM and its aliases. Both are getting written to your host machine's
# /etc/hosts file.
# 
# Please make sure to always provide the hostname *without* a "www." prefixing it.
aliases: 
  - www.baufoerderer-v3.test
  - xhprof.baufoerderer-v3.test

#######################################################################################
#                                                                                     #
# Features                                                                            #
#                                                                                     #  
#######################################################################################