---
# Guest machine user
vm_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"
# www_user: "www-data"
www_user: "vagrant"

#
# PHP
# 
php_version: "7.3"
php_date_timezone: "Europe/Berlin"
php_enable_php_fpm: true
php_display_errors: 1
php_display_startup_errors: 1
php_error_reporting: E_ALL
php_memory_limit: "192M"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"
php_packages_extra: 
  - php{{ php_version }}-intl

#
# Composer
# 
composer_path: /usr/bin/composer
composer_home_path: "/home/{{ vm_user }}/.composer"
composer_home_owner: "{{ vm_user }}"
composer_home_group: "{{ vm_user }}"
composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }

#
# apt
# 
apt_extra_ppa: []
  
apt_extra_packages:
  - silversearcher-ag
  - python3-pip
  - aptitude
  - apache2
  - sqlite
  - unzip

#
# Python packages
# 
pip_extra_packages:
  - virtualenv
  - pyopenssl

#
# MySQL
#
mysql_databases:
  - name: "dev"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "dev"
    host: "%"
    password: "dev"
    priv: "dev.*:ALL"

mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300

#
# Apache
# 
apache_listen_port: 81
apache_listen_port_ssl: 443

apache_packages_state: latest
apache_mods_enabled:
  - headers.load
  - rewrite.load
  - deflate.load
  - expires.load
  - ssl.load
  - proxy.load
  - proxy_fcgi.load

# Helper to set main vhost docroot
apache_docroot: "/var/www/{{ hostname }}/docroot"

# Helper variable to configure the PHP-FPM connection for each Apache
# VirtualHost in the `apache_vhosts` list.
# 
# We need at least Apache 2.4.9 for this to work - otherwise, we would have
# to resort to ProxyPassMatch, which will ignore any mod_rewrite directives.
# 
# See:
# - https://wiki.apache.org/httpd/PHP-FPM
# - https://stackoverflow.com/a/29062114
# - https://askubuntu.com/a/935343
apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://127.0.0.1:9000"
    </FilesMatch>

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
# View the geerlingguy.apache Ansible Role README for more options.
apache_remove_default_vhost: true
apache_vhosts:
  - servername: "{{ hostname }}"
    serveralias: "www.{{ hostname }}"
    documentroot: "{{ apache_docroot }}"
    extra_parameters: |
          {{ apache_vhost_php_fpm_parameters }}
          SetEnv DEV_MACHINE true

  - servername: "xhprof.{{ hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: |
          {{ apache_vhost_php_fpm_parameters }}
          SetEnv DEV_MACHINE true

apache_vhosts_ssl:
  - servername: "{{ hostname }}"
    documentroot: "{{ apache_docroot }}"
    certificate_file: "{{ certificate_file }}"
    certificate_key_file: "/etc/ssl/{{ hostname }}/{{ hostname }}.key"
    extra_parameters: |
          {{ apache_vhost_php_fpm_parameters }}
          SetEnv DEV_MACHINE true

  - servername: "xhprof.{{ hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    certificate_file: "{{ certificate_file }}"
    certificate_key_file: "/etc/ssl/{{ hostname }}/{{ hostname }}.key"
    extra_parameters: |
          {{ apache_vhost_php_fpm_parameters }}
          SetEnv DEV_MACHINE true

#
# Firewall
#
firewall_enabled: true
firewall_log_dropped_packets: false
firewall_disable_firewalld: true
firewall_disable_ufw: true
firewall_allowed_tcp_ports:
  - "22"    # SSH
  - "25"    # SMTP
  - "80"    # HTTP
  - "443"   # TLS/SSL
  - "8025"  # Mailhog - visit https://{hostname}:8025
  - "3306"  # MySQL
  - "35729" # Livereload
