# 
# Extensive documentation regarding Yaml (and what Ruby makes of it) can be found in
# Ruby's Yaml cookbook:
# 
# http://yaml.org/YAML_for_ruby.html
# 
---
- hosts: guest
  become: yes
  become_user: root

  # Props & Values

  vars_files:
    - vars/main.yml
    # - ../../.project/config.yml
   
  # Preflight

  pre_tasks:

    # See https://www.jeffgeerling.com/blog/2016/require-minimum-ansible-version-your-playbook
    # 
    - name: Verify Ansible version requirements.
      assert:
        that: "ansible_version.full is version_compare('2.7.1', '>=')"
        msg: Ansible >= 2.7.1 required, please update.

  # Play

  tasks:

    - include_role:
        name: common
    - include_role:
        name: geerlingguy.firewall
    # - include_role:
    #     name: geerlingguy.pip
    # - include_role:
    #     name: geerlingguy.memcached
    # - include_role:
    #     name: geerlingguy.php-versions
    # - include_role:
    #     name: geerlingguy.php
    # - include_role:
    #     name: geerlingguy.php-mysql
    # - include_role:
    #     name: geerlingguy.php-memcached
    # - include_role:
    #     name: geerlingguy.apache
    # - include_role:
    #     name: geerlingguy.apache-php-fpm
    # - include_role:
    #     name: geerlingguy.mysql
    # - include_role:
    #     name: geerlingguy.mailhog
    # - include_role:
    #     name: geerlingguy.composer
    
    # - name: Add VM user to web server group
    #   user: 
    #     name: vagrant 
    #     groups: www-data 
    #     append: yes

    # - name: Chown /var/www (non-recursively)
    #   file:
    #     path: /var/www
    #     owner: "{{ www_user }}"
    #     group: "{{ www_user }}"
    #     mode: "u+rw,g+rw,o-w"

    # Default tasks

    # - include: ./tasks/default.yml

  # post_tasks:

  #   - name: Restart services
  #     command: echo "Restarting web services"
  #     notify: "restart web services"

  # handlers:

  #   - name: Restart Memcached
  #     service: name=memcached state=restarted
  #     listen: "restart web services"

  #   - name: Restart Apache
  #     service: name=apache2 state=restarted
  #     listen: "restart web services"

  #   - name: Restart PHP-FPM
  #     service: name="php{{ php_version }}-fpm" state=restarted
  #     listen: "restart web services"
